### ISSUE TITLE
Enhance Admin area

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#134]
Summary issue to track results of discussions in various other issues.
- [x] remove the In DOAJ? checkbox, and add a button to the top of the journal edit page.
  
  If the journal is NOT in the DOAJ, it will be a green button "Add journal to DOAJ".
  If it is already in the DOAJ, it will be a red button "Remove journal from DOAJ".
  (#126)
- [x] managing a journal (#84)
- [x] In the journal Admin area, we need the journal contact email address AND NAME shown with the journal record (#118)
- [x] create a journal from an application ("Approve" an application) (#85)
- [ ] tools to help associate the right account with a suggestion (#105)
- [x] subject classification tree UI component and integration into edit a journal form (#86) [afterwards, into Edit an Application form as well]
- [x] comb through #101 to get what actually needs changing and record as tasks here
- [x] redevelop the Edit an Application page to contain a copy of the new Application form + a few extras (subject browser classification, application status) (#83)
- [x] add a new page to the admin area: "Full DOAJ search with ID-s" (#127)
- [ ] show only subjects in the Subjects: part of records, currently keywords are shown too (https://github.com/DOAJ/doaj/issues/132#issuecomment-38146891)
- [x] display comments in journal records
- [x] enhance the Admin Journals page with an "owner" facet and enabling search of journals by username. These would be added to the "search by ..." box as options and of course will work if you simply type into the freetext search box. (#4)
- [ ] rename Classification facet on Journals page to Subject https://github.com/DOAJ/doaj/issues/134#issuecomment-39572691
- [x] add notes to a journal and a suggestion
- [ ] make sure journal / suggestion keywords show up correctly https://github.com/DOAJ/doaj/issues/101#issuecomment-38147084
- ~~[ ] delete "" (blanks or pure whitespace) from alternative_title on journals and suggestions in a small migrate script + check xwalk to make sure it's generating the right stuff. Actually blanks shouldn't show up in facetview, so this is some weird whitespace thing.~~ minor data cleanup
- ~~[ ] split out the time from the date: 'T' is part of the day value. e.g. Date applied: 2014-03-20T08:56:03Z. Can these be broken out? i.e. a space be added?~~ no need, that's not the issue
