### ISSUE TITLE
Feature enhancements to the Application Form

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#137]
The following changes to the Application Form have been requested.

- [ ] allow only 1 URL per URL field
- [ ] pre-fill suggestion form with certain values if the user is logged in, #105 (comment)
- [x] add new question to Application Form: "publishers should provide publication dates on their article pages"
- [x] disable other choices when exclusive checkbox is ticked on page load as well as on ticking the checkbox (fixed during phase2)
- [ ] disallow the same value to be entered in Questions 4 and 5
- [x] allow multiple APCs per journal (will not be done this time around.)
- [x] add boxes for URLs to Questions 13 and 16
- [x] Question 23: add an N/A option and move the question to come after Question 18 instead.
- [ ] Question 25: add CINES and PKP PN as options and change question wording to: 'In which digital archive(s) is the journal content being actively preserved?'.
- [x] Question 30: Change question text to 'Are download statistics displayed publicly for each article?'
- [x] Question 34: change text to 'Maximum 6. Keywords must be in English and in lower case.'
- [ ] Question 34: change question text to 'Add keyword(s) that best describe the subject matter of the journal'
- [x] Question 36: add a free text box field to allow for at least 5 members' names, email addresses and affiliation information.
- [ ] Question 37: change from dropdown to tickboxes. Add 'Post-publication peer review' and 'Other' options. Allow multiple selection. Add a note: 'Editorial review is only valid for journals in the Humanities.'
- [x] Question 41: change question text to 'Does the journal actively check for plagiarism?'
- [x] Question 42: change note text to 'Describe how this is done, including any use of automated software'
- [ ] Question 43: suggestion: should we use time to first decision instead because time to publication is dependent very much on the time authors take to return proofs etc?
- [ ] Question 45: change the question text to: 'Does the journal display licensing information in each full text (HTML or PDF) article?' and add change the help text to 'Licensing information must be displayed on every PDF or in every full text HTML article. We do not accept licensing information that is only displayed in other parts of the site.'
- [x] Question 47: add CC BY NC-SA
- [x] Question 47: remove the 'No' option
- [x] Question 49: make compulsory
- [x] Question 51: remove OAKlist. OAKlist has been decommissioned.
- [x] Question 51: reword the question and add help text. @emanuil-tolev: may have been done by now? #972
- [ ] Question 51: add MALENA as a new option
- [x] Question 52: remove 'Other'.
- [x] Question 54: remove 'Other'.
- [ ] If someone clicks 'Unlock and Close' without saving changes, they get a prompt: 'There are unsaved changes on this page. Continuing will close this record without saving your changes. Do you wish to continue?' (from #386)
- [x] Contextual links, e.g. Archiving, Article identifiers and Deposit policy etc. Make the things clickable, that is the have a hyperlink for LOCKSS, CLOCKSS etc - especially the more exotic handle services and deposit policy services are not well known. "OK, sure, though might take an hour or two (a. making the text of a checkbox a link; b. finding a maintainable way of defining those links in the code, we do have 57 questions and lots of checkboxes). Probably best done with a list of items that you would like hyperlinked, and the relevant URL-s - you know far more than me which ones need a link. Also, the links can be the standard browser blue or (similar to question numbering below) the DOAJ orange, if needed. I think it's also probably a good idea to open these links in a new tab considering you'd otherwise leave the huge form."
- [ ] Add something about TDM licensing: http://www.elsevier.com/about/company-information/policies/text-and-data-mining/elsevier-tdm-license/ - for the future
- [ ] Add a checkbox and field which indicates that the application is a continuation, i.e. This journal is a continuation of [ENTER ISSN] and [TITLE].
- [ ] Add 2 new fields for ISNI numbers under Society and Publisher

**Comment by dommitchell** [comment]
@emanuil-tolev I've just unchecked 'Add CC BY NC-SA (question 47)' as it hasn't actually been done. Or have I missed it somewhere?

**Comment by emanuil-tolev** [comment]
should probably discuss in a meeting, doesn't seem to have been put in any specific milestone yet, and some of them do need more work than just changing text

**Comment by emanuil-tolev** [comment]
> @emanuil-tolev I've just unchecked 'Add CC BY NC-SA (question 47)' as it hasn't actually been done. Or have I missed it somewhere?

added now, check https://doaj.org/admin/journal/ff2069d96721495789b6da721d7f2b7a

**Comment by richard-jones** [comment]
@ClaraDOAJ @greboun - can you clarify what is needed for the new question:

 'add new question to Application Form: "publishers should provide publication dates on their article pages"'

Is this to be a Yes/No question?

**Comment by richard-jones** [comment]
@ClaraDOAJ @greboun:

"Question 23: add an N/A option and move the question to come after Question 18 instead."

At the moment this question has a Yes/No option, which in turn just determines whether to record the URL provided in the conditional field which appears on selection of "Yes".  This means that adding an N/A will be exactly the same as selecting No.  Can we just update the label "No" to "No/Not Applicable", or do you explicitly need to know the difference between "No" and "Not Applicable"?

**Comment by greboun** [comment]
just update the label "No" to "No/Not Applicable"
and move the question 23 to come after Q 18

N/A is just whenever there ARE NO APC OR SUBMISSION CHARGES
In both cases No or N/A we do not need  a URL



Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by greboun** [comment]
@richardjones
This question is to be phrased as a Yes No  question
'do publishers provide dates on article pages'


another item still to be aided according to theTnM  list is 'something on
TDM'
I propose to rephrase Q27 and add a conditional field with the link for the
TDM licensing information
Text & Data Ming TDM: Does the journal allow anyone to use software /
spiders to automatically crawl and extract the journal content ?
[If yes a link to licensing description has to be given in a conditional
field]

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by richard-jones** [comment]
@ClaraDOAJ @greboun 

There's an item which is at the moment just a suggestion, do you want to make this change?

"Question 43: suggestion: should we use time to first decision instead because time to publication is dependent very much on the time authors take to return proofs etc?"

If we do change this, it will change the meaning of the field, which would make all the current data potentially inaccurate.  How do you want to proceed?

**Comment by richard-jones** [comment]
@ClaraDOAJ @greboun 

"Question 51: reword the question and add help text."

Do you know how you want the question and help text reworded?

Also, there was a note against this saying that it may have been done under #972 but it didn't come under that issue, so still needs to be done.

**Comment by richard-jones** [comment]
Just a note for later: some of these changes make the current data in the database invalid - it will be possible to load the applications into the form, but you won't be able to save the form again without answering the new questions, or the questions which have gone from being optional to being required.

**Comment by richard-jones** [comment]
@ClaraDOAJ @greboun 

For the addition of contextual links, I've been able to find suitable links for most external services, but I haven't been able to find the deposit policy service "Héloïse" - do you have a reference?

**Comment by richard-jones** [comment]
http://openaccess.eprints.org/index.php?/archives/903-Frances-Heloise-Directory-of-Publisher-Policies-on-Author-Open-Access-Self-Archiving.html

**Comment by richard-jones** [comment]
http://heloise.ccsd.cnrs.fr/index/index/

**Comment by richard-jones** [comment]
http://heloise.ccsd.cnrs.fr/?lang=en

**Comment by dommitchell** [comment]
I have unchecked ' Question 25: add CINES and PKP PLN as options' as this doesn't seem to have been done. @emanuil-tolev Wondering if it has been incorporated into another task?

I would like to discuss this issue at a next meeting.

**Comment by dommitchell** [comment]
@richard-jones there is one pressing item on this list which we would like to have done asap.

Question 25: add CINES and PKP PLN as options

Cines have been waiting for 2 years and PKP, one year. I kept putting them off until the end of the eapp project. I can't pu them off another year. Is there anyway that this one item can be included in the pre-Refactor work please?

**Comment by dommitchell** [comment]
Richard confirmed over email that CINES and PKP PLN can be done pre-ReFactor.
