### ISSUE TITLE
Final touches on reapplication

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#410]
## Fix before end of reapplication project

- [x] Reapply tab should not have the sidebar. None of the publisher area pages should have the sidebar. Refactor how the sidebar is shown if needed. request.path is accessible in jinja for suffix tests like if it ends in publisher, or admin, or account.

RJ: are we sure about this?  All of the pages except the search pages /do/ have the sidebar, so this would be changing things from the way they currently are on the live site.  @dommitchell - any preference on this?

- [x] If possible, don't put in default values of No policy in place and No for q13, q17, q23, q26, q35, q49. This will force users to fill them in as they're required. - #525 

RJ: unfortunately, for each of these questions, omission of a field means "No", and presence of a field means "Yes".  So it is impossible to tell the difference between a deliberately missing field, and a field that has not yet been completed.  That means we either stick with the current situation, or we wilfully blank out these questions in the CSV, whether they were previously populated or not (and maybe they wouldn't be?).  It will be much much harder to do the same thing for the UI (thought not impossible).  

## Not to fix for the time being

- [x] ```Spanish``` or ```spanish``` not detected as valid choice in CSV question 33. Application form shows ```Spanish; Castilian``` (works when matched exactly) - SE

RJ: Without developing a dictionary of "alternative" names for languages ourselves, it will be difficult to do anything about this.  The ISO list is our reference point, so we need to be careful not to divert from it unless necessary.

- [x] ~~'View associated journal' should be 'View associated journal record' from https://github.com/DOAJ/doaj/issues/321#issuecomment-64784491~~

- [x] Chrome issue - when you submit a form, it remembers the position of the page you were on (i.e. vertically, where you were exactly). From then on when you open that page it will always scroll to that position. Even if you submit the form again from the top of the page, it will always scroll back down to where you FIRST where. This is some kind of botched usability feature.
    - This could be a problem (low priority) on all public application, publisher reapplication, admin+editor application and journal forms. I guess more so for the admins and editors.
    - Consider fix where the page is always focussed on the top if no anchor is present. (We do want the page to focus on the first error or a specific question if that's the link people have followed/entered.)

## Fixed

- [x] Language field does not display the language if it the currently value is not strictly the ISO code for it.  See #465 
- [x] #380 find a record with q9 and q10 populated
- [x] portality.reapplication:225 - save the whole traceback in a separate field
- [x] uploading the hindawi csv as-is (as I've downloaded it from their reapply tab) causes an unexpected error, investigating
- [x] "You may still edit it until a DOAJ administrator picks it up for review." suggest DOAJ editor as wording instead
- [x] What does the double asterisk mean in the spreadsheet? "Amount **"

- [x] Careful with the humongous spreadsheets. Check memory usage in Excel 2007 @emanuil-tolev and make sure to note people should use Excel 2007 or later (http://stackoverflow.com/questions/9424630/how-many-is-too-many-columns-safely-in-excel) for files with > 256 columns

- [x] 438 admin view on test for Hindawi reapps. But Hindawi Updates in progress and their CSV both have 402 reapps. Hmm?

    RJ: CSVs are by account, not publisher name.  This is the correct number for that account

- [x] ISSNs are not editable when contact fields are empty. 
    http://test.doaj.cottagelabs.com/publisher/reapply/001416de0e57439d89e89cc74db714cc . This is very recent live data so ask me for user/pass, I can't put it here.
    #396 says

> Check that the ISSN fields, and the contact fields are disabled (unless the contact fields are empty, in which case they should be editable)

RJ: wording issue - the ISSN fields are never editable, only the contact fields

- [x] error ```Unable to locate a ReApplication with the issn ; spreadsheet is invalid``` on CSV without missing ISSNs

    the file (and account to use): https://dl.dropboxusercontent.com/u/1706997/01013122.csv

- [x] Check that current_application has been removed from the journal
    - this does happen. Because indeed, the application is now obsolete. A new reapp may be filed for that journal later.

- [x] Editors can't save reapplications, the forms are invalid
    - Check that you can "submit" the application without changes (i.e. it should already be "valid")
    - this doesn't work because the contacts from q9, q10, q11 are not copied over automatically to q54, q55, q56 respectively
    - this is critical to fix before user testing starts, it breaks the editor workflow severely - but should be very easy
    - @emanuil-tolev has made a fix for this, but not sure if it's the right one. Is the suggester of a reapplication the same as the contact for the associated journal? Or is the suggester the publisher who is uploading the CSV? @dommitchell ?
        - @dommitchell says copy from q9, q10 and q11

- [x] PR #427 Small but important problem with the error report on the csv-s @dommitchell . This is a **wording** issue only.
    
    - This CSV: https://www.dropbox.com/s/pb3y2x3f4p98e7a/1110662x.csv?dl=0
    - Produces this error report: https://www.dropbox.com/s/01bzs8r755qr6zp/reapplication_errors_20141121.csv?dl=0
    - Note how q9 is required - Name of contact. But the wording on the question says MAY NOT BE EDITED. Meaning it may not be edited if it's already there - but if it's empty, it's actually required!

- [x] PR #430 q50 and q52: typing "No" into the spreadsheet turns it into Other -> "No" instead of just the "No" answer. Whose value is actually "False". Some kind of translation when ingesting the spreadsheet needed.

- [x] q54, q55, q56 need to be filled in from q9, q10 and q11 even when a reapp is submitted from the UI (critical).

- [x] provide lists in #421

- [x] q51 and q53 in the spreadsheet (url questions) are conditionally required - they are not required if the answer to q50 and q52 respectively is "No". Currently they are always required in a spreadsheet, which is not consistent with the web form. SE: logic works fine. Added asterisk. 

- [x] 57 instead of 58 expected csv when accounting for facet count bug size 1000, double check but low priority

    RJ: see issue #413 

- [x] Inconsistencies between 're-application' and 'ReApplication' in UI text

- [x] Change all variations of 'Re-application' to 'Reapplication'.

- [x] Typo on error page - see screenshot below.
'The Re-Applicitation for the above title has already been submitted to the DOAJ administrators, and can no longer be edited.' Should be 'Reapplication' with no hyphen. Change the message to read:
'The DOAJ Editorial Team has already started working on this reapplication so you may no longer edit it.'

- [x] q24 is marked as required, but it's only conditionally required (it does work as such, it's just mark wrong with one * instead of **) SE: added asterisk

- [x] PR #445 Page refresh on CSV upload page causes resubmission (including the form resubmission dialogue box) and re-upload of the last file, while UI does not show any file selected
    - I suppose since it warns you that isn't an issue.
    - [x] start doing a redirect after the POST

- [x] PR #444 Other - None problem in http://test.doaj.cottagelabs.com/publisher/reapply/001416de0e57439d89e89cc74db714cc#publishing_rights-container logged in as the publisher. The question just above it did not have the problem. I had done a very quick fix for this and remember I only changed 1 line, so the other line for the other question must be changed in the same way.

- [x] PR #456 As a publisher that does not have a CSV:

    - That the sticky note is visible on the "Your Journals" tab
        - it isn't visible for account username GJSS on http://test.doaj.cottagelabs.com

SE: the owner query didn't match "GJSS" because a term query is un-analysed in ES. Changed to use a match query.

- [x] PR #474 delete_rejected.py script does not produce a valid backup - SE

```python
def load(filename):
    with open(filename, 'rb') as f:
        content = f.read()
    return content
raw = load('rejected_applications.json')
import json
restore = json.loads(raw)
# => ValueError: Extra data: line 1 column 3817 - line 1 column 21810010 (char 3816 - 21810009)
```

- [x] PR #487 Link to csv file help on downloads page. See #429, #435 - SE

RJ: Since we also have the sheets of country/language codes, perhaps this can all be in one sheet or download

- [x] #440 date added to DOAJ is being overwritten

- [x] Cell references in large error reports can be wrong.

    see #446

**Comment by emanuil-tolev** [comment]
Closing this, everything important was done.
